codecov:
  strict_yaml_branch: master  # only use the latest copy on master branch

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    patch: off
    project:
      default:
        # basic
        target: 90%
