allowBuilds:
  core-js: true
  core-js-pure: true
  esbuild: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - parse-path@5.0.0
  - parse-url@8.1.0
  - braces@3.0.3
  - micromatch@4.0.8
  - ansi-html@0.0.8
  - vue-template-compiler@3.0.0
  - serialize-javascript@7.0.3
  - serialize-javascript@7.0.5
overrides:
  webpackbar: "7.0.0"
