/// <reference types="node" />

import { execFileSync } from 'node:child_process';
import {
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const repositoryRoot = join(__dirname, '..');
const mdGenerateScript = join(repositoryRoot, 'scripts/md-generate.mjs');
const generateIndexScript = join(repositoryRoot, 'scripts/generate-index.mjs');

describe('documentation and index generation', () => {
  let fixtureRoot: string;

  beforeEach(() => {
    fixtureRoot = mkdtempSync(join(tmpdir(), 'common-utils-generation-'));
    writeFileSync(join(fixtureRoot, 'package.json'), '{"type":"module"}');
  });

  afterEach(() => rmSync(fixtureRoot, { recursive: true, force: true }));

  it('generates markdown titles, source links, ignores tagged utilities, and removes stale files', () => {
    mkdirSync(join(fixtureRoot, 'docs-md', 'api'), { recursive: true });
    writeFileSync(join(fixtureRoot, 'docs-md', 'api', 'stale.md'), 'stale');
    const utilityDirectory = join(fixtureRoot, 'src', 'hello-world');
    const ignoredDirectory = join(fixtureRoot, 'src', 'ignored');
    mkdirSync(utilityDirectory, { recursive: true });
    mkdirSync(ignoredDirectory, { recursive: true });
    writeFileSync(
      join(utilityDirectory, 'hello-world.ts'),
      '/**\n * Hello world.\n * @module helloWorld\n * @function helloWorld\n * @name helloWorld\n */\nexport const helloWorld = () => "hello";\n'
    );
    writeFileSync(
      join(ignoredDirectory, 'ignored.ts'),
      '/** @ignore */\nexport const ignored = () => "ignored";\n'
    );

    execFileSync(process.execPath, [mdGenerateScript], { cwd: fixtureRoot });

    const output = readFileSync(
      join(fixtureRoot, 'docs-md', 'api', 'helloWorld.md'),
      'utf8'
    );
    expect(output).toContain('# helloWorld');
    expect(output).toContain(
      'Source: [hello-world.ts](https://github.com/iamdevlinph/common-utils-pkg/blob/main/src/hello-world/hello-world.ts#L7-L7)'
    );
    expect(() =>
      readFileSync(join(fixtureRoot, 'docs-md', 'api', 'stale.md'))
    ).toThrow();
    expect(() =>
      readFileSync(join(fixtureRoot, 'docs-md', 'api', 'ignored.md'))
    ).toThrow();
  });

  it('generates camelCase exports and skips directories without source files', () => {
    mkdirSync(join(fixtureRoot, 'src', 'hello-world'), { recursive: true });
    mkdirSync(join(fixtureRoot, 'src', 'missing-utility'), { recursive: true });
    writeFileSync(
      join(fixtureRoot, 'src', 'hello-world', 'hello-world.ts'),
      'export const helloWorld = () => "hello";\n'
    );

    execFileSync(process.execPath, [generateIndexScript], { cwd: fixtureRoot });

    expect(readFileSync(join(fixtureRoot, 'src', 'index.ts'), 'utf8')).toBe(
      "export { helloWorld } from './hello-world/hello-world';\n"
    );
  });

  it('preserves the canonical browserDetect markdown byte-for-byte', () => {
    const expected = `<!-- Generated by documentation.js. Update this documentation by updating the source code. -->

# browserDetect

Detects browser being used.

### Examples

\`\`\`javascript
browserDetect();
// => 'Chrome
\`\`\`

Returns **[string][1]** of browser name.

**Meta**

*   **version**: 3.1.0

[1]: https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/String


* Source: [browser-detect.ts](https://github.com/iamdevlinph/common-utils-pkg/blob/main/src/browser-detect/browser-detect.ts#L17-L52)`;
    const sourceDirectory = join(fixtureRoot, 'src', 'browser-detect');
    mkdirSync(sourceDirectory, { recursive: true });
    writeFileSync(
      join(sourceDirectory, 'browser-detect.ts'),
      readFileSync(
        join(repositoryRoot, 'src/browser-detect/browser-detect.ts'),
        'utf8'
      )
    );
    execFileSync(process.execPath, [mdGenerateScript], { cwd: fixtureRoot });
    const actual = readFileSync(
      join(fixtureRoot, 'docs-md/api/browserDetect.md'),
      'utf8'
    ).replace(/\n$/, '');

    expect(actual).toBe(expected);
  });

  it('uses the common markdown layout for every generated API page', () => {
    for (const filename of readdirSync(join(repositoryRoot, 'docs-md/api'))) {
      if (!filename.endsWith('.md')) continue;
      const markdown = readFileSync(
        join(repositoryRoot, 'docs-md/api', filename),
        'utf8'
      );
      expect(markdown).toMatch(
        /^<!-- Generated by documentation\.js\..* -->\n\n# \S+\n\n/
      );
      expect(markdown).not.toMatch(/-->##|###\S|```javascript\S/);
      expect(markdown).toMatch(/\n\n\n\* Source: \[[^\]]+\.ts\]\([^\n]+\)$/);
      expect(markdown).not.toMatch(/\S(###|```|\*\*Meta\*\*)/);
    }
  });
});
